# Include hook code here

require 'basichacks/classhack'
require 'basichacks/datehack'
require 'basichacks/timehack'
require 'basichacks/hashhack'
require 'basichacks/stringhack'
#RAILS3 require 'basichacks/activerecordhack'
require 'basichacks/arrayhack'
require 'basichacks/objecthack'
require 'basichacks/floathack'
require 'basichacks/enumerablehack'
require 'basichacks/numerichack'
require 'basichacks/truefalsehack'
require 'basichacks/fixnumhack'
require 'basichacks/formhelperhack'
#RAILS3 require 'basichacks/actionmailerhack'
require 'basichacks/puts'
require 'basichacks/cachehack'
