class Breadcrumb
  attr_accessor :name, :options

  def initialize(name, options = {})
    @name = name
    @options = options
  end

  # Given an action name, return the correct breadcrumb
  def Breadcrumb.for_action(controller_name, action_name)
    self.send("for_#{controller_name}_#{action_name}".to_sym)
  end

  # Return a breadcrumb for a particular category name
  def Breadcrumb.for_category(category)
    category = Category.find(category) if !category.instance_of?(Category)
    trail = self.for_store_index()
    if (!category.toplevel?)
      trail << Breadcrumb.new(category.parent.name, {:action => :category, :id => category.parent.id, :name => ApplicationHelper.link_seo_for(category.parent.name)})
    end
    trail << Breadcrumb.new(category.name, {:action => :category, :id => category.id, :name => ApplicationHelper.link_seo_for(category.name)})
    return trail
  end

  def Breadcrumb.for_universities
    trail =  Breadcrumb.for_store_index 
    trail << Breadcrumb.new("SmartFlix Universities", {:action => :universities})
    return trail
  end

  def Breadcrumb.for_author(author)
    author = Author.find(author) if !author.instance_of?(Author)
    trail = self.for_store_index()
    trail << Breadcrumb.new(author.name, {:action => :author, :id => author.id, :name => ApplicationHelper.link_seo_for(author.name)})
    return trail
  end

  # XYZFIX P4: it stinks that we have to pass the url in here, but
  #  * no combination of :controller, :action, and :id gets us the URL we want
  #  * that url can only be generated by the link helper functions
  #  * we don't have access to the link helper functions from inside a model
  #  * tricks like 'include ApplicationHelper' don't work
  #  * creating a trampoline function inside application helper doesn't work
  def Breadcrumb.for_wiki(wiki_page = nil, wiki_url = nil)
    trail =  Breadcrumb.for_store_index
    trail << Breadcrumb.new('How-To Articles', {:controller => 'articles'}) 
    if wiki_page
      name = wiki_page.name || "new"
      trail << Breadcrumb.new(name, { :url => wiki_url })
    end
    trail
  end

  def Breadcrumb.for_wiki_edit(wiki_page, wiki_url = nil)
    trails =     Breadcrumb.for_wiki(wiki_page, wiki_url)
    trails << Breadcrumb.new("edit", {})
  end

  def Breadcrumb.for_wiki_new()
    trails =  Breadcrumb.for_store_index
    trails << Breadcrumb.new('How-To Articles', {:controller => 'articles'}) 
    trails << Breadcrumb.new("write a new article", {})
  end

  def Breadcrumb.for_store_index()
    return [Breadcrumb.new('SmartFlix How-To Videos', {:controller => 'store'})]
  end
  def Breadcrumb.for_store_search()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Search', {:controller => 'store', :action => 'search'})]
  end
  def Breadcrumb.for_store_new()
    return Breadcrumb.for_store_index + [Breadcrumb.new('New Titles on DVD', {:controller => 'store', :action => 'new'})]
  end
  def Breadcrumb.for_store_top_rated()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Top Rated Titles on DVD', {:controller => 'store', :action => 'top_rated'})]
  end
  def Breadcrumb.for_store_recommended()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Recommended Titles', {:controller => 'store', :action => 'recommended'})]
  end
  def Breadcrumb.for_store_how_it_works()
    return Breadcrumb.for_store_index + [Breadcrumb.new('How It Works', {:controller => 'store', :action => 'how_it_works'})]
  end
  def Breadcrumb.for_store_testimonials()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Testimonials', {:controller => 'store', :action => 'testimonials'})]
  end
  def Breadcrumb.for_store_smartblog()
    return Breadcrumb.for_store_index + [Breadcrumb.new('SmartBlog', {:controller => 'store', :action => 'smartblog'})]
  end
  def Breadcrumb.for_store_about_us()
    return Breadcrumb.for_store_index + [Breadcrumb.new('About Us', {:controller => 'store', :action => 'about_us'})]
  end
  def Breadcrumb.for_store_press()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Press', {:controller => 'store', :action => 'press'})]
  end
  def Breadcrumb.for_store_contest_rules()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Contest Rules', {:controller => 'store', :action => 'contest_rules'})]
  end
  def Breadcrumb.for_store_contact_us()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Contact Us', {:controller => 'store', :action => 'contact_us'})]
  end
  def Breadcrumb.for_store_suggest()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Suggestions', {:controller => 'store', :action => 'suggest'})]
  end
  def Breadcrumb.for_store_conditions()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Terms and Conditions', {:controller => 'store', :action => 'conditions'})]
  end
  def Breadcrumb.for_store_image_submission_policy()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Image Submission Policy', {:controller => 'store', :action => 'image_submission_policy'})]
  end
  def Breadcrumb.for_store_privacy()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Privacy Policy', {:controller => 'store', :action => 'privacy'})]
  end
  def Breadcrumb.for_store_redeem()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Redeem Gift Certificate', {:controller => 'store', :action => 'redeem'})]
  end
  def Breadcrumb.for_store_giftcert()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Gift Certificates', {:controller => 'store', :action => 'giftcert'})]
  end
  def Breadcrumb.for_store_giftcard()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Gift Card Redemption', {:controller => 'store', :action => 'giftcard'})]
  end
  def Breadcrumb.for_store_categories
    return Breadcrumb.for_store_index + [Breadcrumb.new('All Categories', {:controller => 'store', :action => 'categories'})]
  end
  def Breadcrumb.for_store_popular
    return Breadcrumb.for_store_index + [Breadcrumb.new('Most Popular', {:controller => 'store', :action => 'popular'})]
  end

  def Breadcrumb.for_help_index()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Help', {:controller => 'help'})]
  end
  def Breadcrumb.for_help_univ_faq()
    return Breadcrumb.for_help_index + [Breadcrumb.new('SmartFlix Universities', {:controller => 'help', :action => 'how_it_works'})]
  end
  def Breadcrumb.for_help_how_it_works()
    return Breadcrumb.for_help_index + [Breadcrumb.new('How It Works', {:controller => 'help', :action => 'how_it_works'})]
  end
  def Breadcrumb.for_help_payment()
    return Breadcrumb.for_help_index + [Breadcrumb.new('Payment', {:controller => 'help', :action => 'payment'})]
  end
  def Breadcrumb.for_help_legal()
    return Breadcrumb.for_help_index + [Breadcrumb.new('Legal', {:controller => 'help', :action => 'legal'})]
  end
  def Breadcrumb.for_help_technical()
    return Breadcrumb.for_help_index + [Breadcrumb.new('Technical', {:controller => 'help', :action => 'technical'})]
  end
  def Breadcrumb.for_help_video_bundles()
    return Breadcrumb.for_help_index + [Breadcrumb.new('Video Bundles', {:controller => 'help', :action => 'video_bundles'})]
  end
  def Breadcrumb.for_help_other()
    return Breadcrumb.for_help_index + [Breadcrumb.new('Other', {:controller => 'help', :action => 'other'})]
  end
  def Breadcrumb.for_help_find
    return Breadcrumb.for_help_index +
      [Breadcrumb.new('Can\'t find what you\'re looking for?', {:controller => "help", :action => "find"} )]
  end

  def Breadcrumb.for_cart_index()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Cart Contents', {:controller => 'cart'})]
  end
  def Breadcrumb.for_cart_checkout()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Checkout', {:controller => 'cart', :action => 'checkout'})]
  end
  def Breadcrumb.for_cart_order_success()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Successful Order', {:controller => 'cart', :action => 'order_success'})]
  end

  def Breadcrumb.for_customer_index()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Account', {:controller => 'customer'})]
  end
  def Breadcrumb.for_customer_login()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Login', {:controller => 'customer', :action => 'login'})]
  end
  def Breadcrumb.for_customer_address()
    return Breadcrumb.for_customer_index + [Breadcrumb.new('Edit Address')]
  end

  #----------
  # univ
  #----------

  def Breadcrumb.for_customer_university()
    return Breadcrumb.for_customer_index + [Breadcrumb.new('Your Queue')]
  end

  def Breadcrumb.for_customer_university_one(order)
    return Breadcrumb.for_customer_index + 
      [Breadcrumb.new('Your Queues', {:controller => 'customer', :action => 'university_status_all'})] +
      [Breadcrumb.new("#{order.university.name}")]
  end

  def Breadcrumb.for_customer_university_plan(order)
    return Breadcrumb.for_customer_index + 
      [Breadcrumb.new('Your Queues', {:controller => 'customer', :action => 'university_status_all'})] +
      [Breadcrumb.new("#{order.university.name}",  {:controller => 'customer', :action => 'university_status', :id => order.id })] +
      [Breadcrumb.new("Plan")] 
  end

  def Breadcrumb.for_customer_university_details(order)
    return Breadcrumb.for_customer_index + 
      [Breadcrumb.new('Your Queues', {:controller => 'customer', :action => 'university_status_all'})] +
      [Breadcrumb.new("#{order.university.name}",  {:controller => 'customer', :action => 'university_status', :id => order.id })] +
      [Breadcrumb.new("Payment")] 
  end


  def Breadcrumb.for_customer_wheres_my_stuff()
    return Breadcrumb.for_customer_index + [Breadcrumb.new("Where\'s My Stuff?")] #"'
  end

  def Breadcrumb.for_customer_order_history()
    return Breadcrumb.for_customer_index + [Breadcrumb.new('Order History', {:controller => 'customer', :action => 'order_history'})]
  end
  def Breadcrumb.for_customer_logout()
    return Breadcrumb.for_customer_index + [Breadcrumb.new('Logout Page')]
  end
  def Breadcrumb.for_customer_password()
    return Breadcrumb.for_customer_index + [Breadcrumb.new("Change Password")]
  end
  def Breadcrumb.for_customer_account_info()
    return Breadcrumb.for_customer_index + [Breadcrumb.new("Address Book")]
  end
  def Breadcrumb.for_customer_reset_password()
    return Breadcrumb.for_customer_index + [Breadcrumb.new("Reset Password")]
  end
  def Breadcrumb.for_customer_email_prefs()
    return Breadcrumb.for_customer_index + [Breadcrumb.new("Change E-mail Preferences")]
  end
  def Breadcrumb.for_customer_report_problem(order)
    return Breadcrumb.for_customer_order(order) + [Breadcrumb.new("Report Problem")]
  end
  def Breadcrumb.for_customer_order(order)
    return Breadcrumb.for_customer_order_history + [Breadcrumb.new("Order ##{order.id}", {:controller => 'customer', :action => 'order', :id => order.id})]
  end
  def Breadcrumb.for_customer_manage_cc()
    return Breadcrumb.for_customer_index + [Breadcrumb.new('Manage Credit Cards')]
  end

  def Breadcrumb.for_affiliate_index()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Affiliate Program', {:controller => 'affiliate'})]
  end

  def Breadcrumb.for_affiliate_agreement()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Affiliate Program', {:controller => 'affiliate'})]
  end

  def Breadcrumb.for_affiliate_introduction()
    return Breadcrumb.for_affiliate_index() + [Breadcrumb.new('Affiliate Introduction', {:controller => 'affiliate', :action => 'introduction'})]
  end

  def Breadcrumb.for_contest_list()
    return Breadcrumb.for_store_index + [Breadcrumb.new('Contests', {:controller => 'contest', :action => ''})]
  end

  def Breadcrumb.for_contest_show(contest)
    return Breadcrumb.for_contest_list + [Breadcrumb.new(contest.title, {:controller => 'contest', :action => 'show', :id => contest})]
  end

  def Breadcrumb.for_contest_enter(contest)
    return Breadcrumb.for_contest_show(contest)
  end

  def Breadcrumb.for_contest_vote(contest)
    return Breadcrumb.for_contest_show(contest)
  end

  def Breadcrumb.for_contest_edit(contest)
    return Breadcrumb.for_contest_show(contest)
  end

  def Breadcrumb.for_wiki_pages_index
    return Breadcrumb.for_store_index
  end
  def Breadcrumb.for_wiki_pages_show
    return Breadcrumb.for_store_index
  end
  def Breadcrumb.for_wiki_pages_new
    return Breadcrumb.for_store_index
  end
  def Breadcrumb.for_wiki_pages_edit
    return Breadcrumb.for_store_index
  end
  def Breadcrumb.for_wiki_pages_create
    return Breadcrumb.for_store_index
  end
  def Breadcrumb.for_wiki_pages_update
    return Breadcrumb.for_store_index
  end

  def Breadcrumb.for_projects_index
    return Breadcrumb.for_store_index + [Breadcrumb.new('All Projects', :controller => 'projects', :action => 'index')]
  end

  def Breadcrumb.for_projects_new
    return Breadcrumb.for_projects_index
  end

  def Breadcrumb.for_projects_show(project)
    return Breadcrumb.for_projects_index + [Breadcrumb.new(project.title, :controller => 'projects', :action => 'show', :id => project)]
  end

  class << self
    def method_missing(*args)
      return Breadcrumb.for_store_index
    end
  end

end
